### ISSUE TITLE
Error when syncing folder with repeating name

### ISSUE THREAD

**Issue by DavidPD** [davidolrik/sublime-rsync-ssh#17]
I'm getting the following error when I try to sync a folder that has it's name repeated in the path:

    Traceback (most recent call last):
      File "./threading.py", line 901, in _bootstrap_inner
      File "/Users/david.dovel/Library/Application Support/Sublime Text 3/Packages/sublime-rsync-ssh/rsync-ssh.py", line 165, in run
        [split_prefix, subfolder] = str.split(remote_key, folder_path_basename, 2)
    ValueError: too many values to unpack (expected 2)

syncing `/Developer/vagrant-proj1/projects/proj1` causes this issue
syncing `/Developer/vagrant-proj1/projects/proj2` does not

**Comment by davidolrik** [comment]
This is fixed in [v1.4.3](https://github.com/davidolrik/sublime-rsync-ssh/releases/tag/v1.4.3).

Let me know if it doesn't work for you.
