### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by aleiku** [davidolrik/sublime-rsync-ssh#18]
Writing file /project-path/app.php with encoding UTF-8 (atomic)
Exception in thread Thread-13:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "rsync-ssh in ~/Library/Application Support/Sublime Text 3/Installed Packages/Rsync SSH.sublime-package", line 151, in run
AttributeError: 'NoneType' object has no attribute 'keys'

my os is 
10.10.2
Sublime Text 3065

**Comment by davidolrik** [comment]
Could you paste your project config?

**Comment by aleiku** [comment]
I fixed,  my bad. I changed the 'remotes' key.
