### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by zuitu** [davidolrik/sublime-rsync-ssh#38]
Hi. Everything was working properly on linux. Now on Windows I get this errors:
```
Here's the full console output on a fresh run:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "rsync_ssh in D:\Program Files\Sublime Text 3\Data\Installed Packages\Rsync SSH.sublime-package", line 460, in run
  File "rsync_ssh in D:\Program Files\Sublime Text 3\Data\Installed Packages\Rsync SSH.sublime-package", line 43, in check_output
  File "./subprocess.py", line 576, in check_output
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by davidolrik** [comment]
I think you are missing `cygpath`, but as I'm not a Windows user I can't say for sure.

If this is indeed the case, let me know and I'll improve the "error message"-

**Comment by leonardomdr** [comment]
I had the same problem.. 

After installing cygwin (64) and adding the "cyg path", which is the default here ("C:\cygwin64\bin") to the Windows PATH variable, it changed the error. Any hint on that?

```
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "rsync_ssh in C:\Users\Leonardo\AppData\Roaming\Sublime Text 3\Installed Packages\Rsync SSH.sublime-package", line 497, in run
  File "rsync_ssh in C:\Users\Leonardo\AppData\Roaming\Sublime Text 3\Installed Packages\Rsync SSH.sublime-package", line 43, in check_output
  File "./python3.3/subprocess.py", line 576, in check_output
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Thank you.

**Comment by luizvasconceloss** [comment]
It's working on my Windows. To configure I did the following steps:
1. Install cygwin with rsync support
2. In the Cygwin terminal run: 'mkpasswd -l > /cygdrive/c/cygwin/etc/passwd' to insert the users and home folders. (check if is pointing to the cygwin install)
3. Run: 'ln -s /cygdrive/c /c' to create a symlink 

An important thing is if you have git installed the ssh command may conflict with the cygwin ssh. I chose to rename the ssh executable provided by git.
