### ISSUE TITLE
Can't initialize settings

### ISSUE THREAD

**Issue by beshur** [davidolrik/sublime-rsync-ssh#48]
Hi.
I tried to init a couple of times settings in my project folder.
Nothing happened, then I opened the console and see this:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "rsync_ssh in /Users/alex.buznik/Library/Application Support/Sublime Text 3/Installed Packages/Rsync SSH.sublime-package", line 124, in run
AttributeError: 'NoneType' object has no attribute 'run_command'
[rsync-ssh] rsync_ssh configuration already exists.
```

No new files were created though.

What could be the problem?

OS X 10.13.2, ST 3.0

**Comment by beshur** [comment]
Sorry, my bad, RTFM
